--------------------------------------------------------
-- Archivo creado  - sábado-septiembre-07-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ARTICULO
--------------------------------------------------------

  CREATE TABLE "CEURIBE"."ARTICULO" 
   (	"IDARTICULO" CHAR(8 BYTE), 
	"IDCATEGORIA" NUMBER(*,0), 
	"NOMARTICULO" VARCHAR2(50 BYTE), 
	"PREARTICULO" NUMBER(10,2)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CATEGORIA
--------------------------------------------------------

  CREATE TABLE "CEURIBE"."CATEGORIA" 
   (	"IDCATEGORIA" NUMBER(*,0), 
	"NOMCATEGORIA" VARCHAR2(25 BYTE), 
	"PREFIJO" CHAR(3 BYTE), 
	"CONCATEGORIA" NUMBER(*,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CLIENTE
--------------------------------------------------------

  CREATE TABLE "CEURIBE"."CLIENTE" 
   (	"IDCLIENTE" CHAR(6 BYTE), 
	"NOMCLIENTE" VARCHAR2(50 BYTE), 
	"RUC" CHAR(11 BYTE), 
	"DIRCLIENTE" VARCHAR2(60 BYTE), 
	"TELCLIENTE" VARCHAR2(20 BYTE), 
	"CLAVE" VARCHAR2(10 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DELIVERY
--------------------------------------------------------

  CREATE TABLE "CEURIBE"."DELIVERY" 
   (	"IDDELIVERY" NUMBER(*,0), 
	"DESDELIVERY" VARCHAR2(15 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DETALLEPEDIDO
--------------------------------------------------------

  CREATE TABLE "CEURIBE"."DETALLEPEDIDO" 
   (	"IDPEDIDO" NUMBER(*,0), 
	"IDARTICULO" CHAR(8 BYTE), 
	"CANTIDAD" NUMBER(*,0), 
	"PREVENTA" NUMBER(10,2), 
	"SUBTOTAL" NUMBER(10,2)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DOCUMENTO
--------------------------------------------------------

  CREATE TABLE "CEURIBE"."DOCUMENTO" 
   (	"IDDOCUMENTO" NUMBER(*,0), 
	"NOMDOCUMENTO" VARCHAR2(20 BYTE), 
	"SERIE" NUMBER(*,0), 
	"CONDOCUMENTO" NUMBER(*,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table EMPLEADO
--------------------------------------------------------

  CREATE TABLE "CEURIBE"."EMPLEADO" 
   (	"IDEMPLEADO" CHAR(6 BYTE), 
	"APEEMPLEADO" VARCHAR2(30 BYTE), 
	"NOMEMPLEADO" VARCHAR2(30 BYTE), 
	"DIREMPLEADO" VARCHAR2(60 BYTE), 
	"TELEMPLEADO" VARCHAR2(20 BYTE), 
	"CLAVE" VARCHAR2(10 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ESTADO
--------------------------------------------------------

  CREATE TABLE "CEURIBE"."ESTADO" 
   (	"IDESTADO" NUMBER(*,0), 
	"DESESTADO" VARCHAR2(15 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PARAMETRO
--------------------------------------------------------

  CREATE TABLE "CEURIBE"."PARAMETRO" 
   (	"CAMPO" VARCHAR2(20 BYTE), 
	"VALOR" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PEDIDO
--------------------------------------------------------

  CREATE TABLE "CEURIBE"."PEDIDO" 
   (	"IDPEDIDO" NUMBER(*,0), 
	"IDDOCUMENTO" NUMBER(*,0), 
	"IDEMPLEADO" CHAR(6 BYTE), 
	"NUMDOCUMENTO" VARCHAR2(15 BYTE), 
	"FECHA" DATE, 
	"IDCLIENTE" CHAR(6 BYTE), 
	"NOMCLIENTE" VARCHAR2(40 BYTE), 
	"IMPORTE" NUMBER(10,2), 
	"DESCUENTO" NUMBER(10,2), 
	"SUBTOTAL" NUMBER(10,2), 
	"IGV" NUMBER(10,2), 
	"TOTAL" NUMBER(10,2), 
	"DELIVERY" NUMBER(*,0) DEFAULT (0), 
	"ESTADO" NUMBER(*,0) DEFAULT (0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PRODUCTO
--------------------------------------------------------

  CREATE TABLE "CEURIBE"."PRODUCTO" 
   (	"CODIGO" CHAR(5 BYTE), 
	"NOMBRE" VARCHAR2(50 BYTE), 
	"COSTO" NUMBER(10,2), 
	"STOCK" NUMBER(10,2)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PROMOCION
--------------------------------------------------------

  CREATE TABLE "CEURIBE"."PROMOCION" 
   (	"IDPROMOCION" NUMBER(*,0), 
	"MONTOMIN" NUMBER(10,2), 
	"MONTOMAX" NUMBER(10,2), 
	"PORCENTAJE" NUMBER(*,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table RESPUESTA
--------------------------------------------------------

  CREATE TABLE "CEURIBE"."RESPUESTA" 
   (	"ID" NUMBER(*,0), 
	"CODIGO" CHAR(5 BYTE), 
	"OPINION" VARCHAR2(50 BYTE), 
	"COMENTARIO" VARCHAR2(100 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table USUARIO
--------------------------------------------------------

  CREATE TABLE "CEURIBE"."USUARIO" 
   (	"CODIGO" CHAR(5 BYTE), 
	"NOMBRES" VARCHAR2(50 BYTE), 
	"APELLIDOS" VARCHAR2(50 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for View VW_LISTARPRODUCTOS
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "CEURIBE"."VW_LISTARPRODUCTOS" ("CODIGO", "NOMBRE", "COSTO", "STOCK") AS 
  SELECT CODIGO, NOMBRE, COSTO, STOCK FROM Producto;
REM INSERTING into CEURIBE.ARTICULO
SET DEFINE OFF;
Insert into CEURIBE.ARTICULO (IDARTICULO,IDCATEGORIA,NOMARTICULO,PREARTICULO) values ('BEB00001','1','Gaseosa (Mediana)','2');
Insert into CEURIBE.ARTICULO (IDARTICULO,IDCATEGORIA,NOMARTICULO,PREARTICULO) values ('BEB00002','1','Gaseosa ( 1 Litro)','3,5');
Insert into CEURIBE.ARTICULO (IDARTICULO,IDCATEGORIA,NOMARTICULO,PREARTICULO) values ('BEB00003','1','Gaseosa (1.5 Litro)','4,5');
Insert into CEURIBE.ARTICULO (IDARTICULO,IDCATEGORIA,NOMARTICULO,PREARTICULO) values ('BEB00004','1','Cerveza Cristal (Chica)','5');
Insert into CEURIBE.ARTICULO (IDARTICULO,IDCATEGORIA,NOMARTICULO,PREARTICULO) values ('COM00001','5','Combo Económico','7,99');
Insert into CEURIBE.ARTICULO (IDARTICULO,IDCATEGORIA,NOMARTICULO,PREARTICULO) values ('COM00002','5','Combo Personal','10,99');
Insert into CEURIBE.ARTICULO (IDARTICULO,IDCATEGORIA,NOMARTICULO,PREARTICULO) values ('COM00003','5','Combo Especial','13,99');
Insert into CEURIBE.ARTICULO (IDARTICULO,IDCATEGORIA,NOMARTICULO,PREARTICULO) values ('COM00004','5','Combo Familiar','28,99');
Insert into CEURIBE.ARTICULO (IDARTICULO,IDCATEGORIA,NOMARTICULO,PREARTICULO) values ('COM00005','5','Combo para dos','16,99');
REM INSERTING into CEURIBE.CATEGORIA
SET DEFINE OFF;
Insert into CEURIBE.CATEGORIA (IDCATEGORIA,NOMCATEGORIA,PREFIJO,CONCATEGORIA) values ('1','Bebidas','BEB','4');
Insert into CEURIBE.CATEGORIA (IDCATEGORIA,NOMCATEGORIA,PREFIJO,CONCATEGORIA) values ('2','Carnes','CAR','0');
Insert into CEURIBE.CATEGORIA (IDCATEGORIA,NOMCATEGORIA,PREFIJO,CONCATEGORIA) values ('3','Pollo','POL','0');
Insert into CEURIBE.CATEGORIA (IDCATEGORIA,NOMCATEGORIA,PREFIJO,CONCATEGORIA) values ('4','Postres','POS','0');
Insert into CEURIBE.CATEGORIA (IDCATEGORIA,NOMCATEGORIA,PREFIJO,CONCATEGORIA) values ('5','Combos','COM','5');
REM INSERTING into CEURIBE.CLIENTE
SET DEFINE OFF;
Insert into CEURIBE.CLIENTE (IDCLIENTE,NOMCLIENTE,RUC,DIRCLIENTE,TELCLIENTE,CLAVE) values ('C00002','Armando Valencia','54788932   ','Magdalena','456-3472','C00002');
Insert into CEURIBE.CLIENTE (IDCLIENTE,NOMCLIENTE,RUC,DIRCLIENTE,TELCLIENTE,CLAVE) values ('C00003','Koky Bustamante','36476284   ','San Martin de Porres','381-0589','C00003');
Insert into CEURIBE.CLIENTE (IDCLIENTE,NOMCLIENTE,RUC,DIRCLIENTE,TELCLIENTE,CLAVE) values ('C00004','Jorge Veramendi','14667934   ','Callao','265-5734','C00004');
Insert into CEURIBE.CLIENTE (IDCLIENTE,NOMCLIENTE,RUC,DIRCLIENTE,TELCLIENTE,CLAVE) values ('C00005','Donisio Rosas','14824794   ','Huacho','512-4744','C00005');
Insert into CEURIBE.CLIENTE (IDCLIENTE,NOMCLIENTE,RUC,DIRCLIENTE,TELCLIENTE,CLAVE) values ('C00006','Abraham Oceda','67458712   ','Los Olivos','525-6723','C00006');
Insert into CEURIBE.CLIENTE (IDCLIENTE,NOMCLIENTE,RUC,DIRCLIENTE,TELCLIENTE,CLAVE) values ('C00007','Jorge Mori','12349876   ','Lima','345-1276','C00007');
Insert into CEURIBE.CLIENTE (IDCLIENTE,NOMCLIENTE,RUC,DIRCLIENTE,TELCLIENTE,CLAVE) values ('C00008','Jose Apari','76234562   ','Lima','768-3782','C00008');
Insert into CEURIBE.CLIENTE (IDCLIENTE,NOMCLIENTE,RUC,DIRCLIENTE,TELCLIENTE,CLAVE) values ('C00010','Maria Carrion','23946154   ','Lima','223-7482','C00010');
REM INSERTING into CEURIBE.DELIVERY
SET DEFINE OFF;
Insert into CEURIBE.DELIVERY (IDDELIVERY,DESDELIVERY) values ('1','EN CAMINO');
Insert into CEURIBE.DELIVERY (IDDELIVERY,DESDELIVERY) values ('2','EN CAMINO');
Insert into CEURIBE.DELIVERY (IDDELIVERY,DESDELIVERY) values ('3','EN TRAFICO');
Insert into CEURIBE.DELIVERY (IDDELIVERY,DESDELIVERY) values ('4','LLEGANDO');
Insert into CEURIBE.DELIVERY (IDDELIVERY,DESDELIVERY) values ('5','ENTREGADO');
REM INSERTING into CEURIBE.DETALLEPEDIDO
SET DEFINE OFF;
Insert into CEURIBE.DETALLEPEDIDO (IDPEDIDO,IDARTICULO,CANTIDAD,PREVENTA,SUBTOTAL) values ('1','P0001   ','1','0','2,34');
Insert into CEURIBE.DETALLEPEDIDO (IDPEDIDO,IDARTICULO,CANTIDAD,PREVENTA,SUBTOTAL) values ('1','P0002   ','1','0','6,45');
Insert into CEURIBE.DETALLEPEDIDO (IDPEDIDO,IDARTICULO,CANTIDAD,PREVENTA,SUBTOTAL) values ('1','P0003   ','1','0','5,3');
Insert into CEURIBE.DETALLEPEDIDO (IDPEDIDO,IDARTICULO,CANTIDAD,PREVENTA,SUBTOTAL) values ('2','P0006   ','1','0','20');
Insert into CEURIBE.DETALLEPEDIDO (IDPEDIDO,IDARTICULO,CANTIDAD,PREVENTA,SUBTOTAL) values ('2','P0007   ','1','0','8,9');
Insert into CEURIBE.DETALLEPEDIDO (IDPEDIDO,IDARTICULO,CANTIDAD,PREVENTA,SUBTOTAL) values ('2','P0008   ','1','0','4,9');
Insert into CEURIBE.DETALLEPEDIDO (IDPEDIDO,IDARTICULO,CANTIDAD,PREVENTA,SUBTOTAL) values ('3','P0011   ','1','0','20');
Insert into CEURIBE.DETALLEPEDIDO (IDPEDIDO,IDARTICULO,CANTIDAD,PREVENTA,SUBTOTAL) values ('3','P0009   ','1','0','8,9');
Insert into CEURIBE.DETALLEPEDIDO (IDPEDIDO,IDARTICULO,CANTIDAD,PREVENTA,SUBTOTAL) values ('3','P0003   ','1','0','4,9');
Insert into CEURIBE.DETALLEPEDIDO (IDPEDIDO,IDARTICULO,CANTIDAD,PREVENTA,SUBTOTAL) values ('4','P0005   ','1','0','20');
Insert into CEURIBE.DETALLEPEDIDO (IDPEDIDO,IDARTICULO,CANTIDAD,PREVENTA,SUBTOTAL) values ('4','P0001   ','1','0','8,9');
Insert into CEURIBE.DETALLEPEDIDO (IDPEDIDO,IDARTICULO,CANTIDAD,PREVENTA,SUBTOTAL) values ('4','P0008   ','1','0','4,9');
Insert into CEURIBE.DETALLEPEDIDO (IDPEDIDO,IDARTICULO,CANTIDAD,PREVENTA,SUBTOTAL) values ('5','P0012   ','1','0','20');
Insert into CEURIBE.DETALLEPEDIDO (IDPEDIDO,IDARTICULO,CANTIDAD,PREVENTA,SUBTOTAL) values ('5','P0011   ','1','0','8,9');
Insert into CEURIBE.DETALLEPEDIDO (IDPEDIDO,IDARTICULO,CANTIDAD,PREVENTA,SUBTOTAL) values ('5','P0013   ','1','0','4,9');
Insert into CEURIBE.DETALLEPEDIDO (IDPEDIDO,IDARTICULO,CANTIDAD,PREVENTA,SUBTOTAL) values ('6','P0012   ','1','0','20');
Insert into CEURIBE.DETALLEPEDIDO (IDPEDIDO,IDARTICULO,CANTIDAD,PREVENTA,SUBTOTAL) values ('6','P0011   ','1','0','8,9');
Insert into CEURIBE.DETALLEPEDIDO (IDPEDIDO,IDARTICULO,CANTIDAD,PREVENTA,SUBTOTAL) values ('6','P0013   ','1','0','4,9');
Insert into CEURIBE.DETALLEPEDIDO (IDPEDIDO,IDARTICULO,CANTIDAD,PREVENTA,SUBTOTAL) values ('7','P0010   ','1','0','20');
Insert into CEURIBE.DETALLEPEDIDO (IDPEDIDO,IDARTICULO,CANTIDAD,PREVENTA,SUBTOTAL) values ('7','P0014   ','1','0','8,9');
Insert into CEURIBE.DETALLEPEDIDO (IDPEDIDO,IDARTICULO,CANTIDAD,PREVENTA,SUBTOTAL) values ('7','P0016   ','1','0','4,9');
Insert into CEURIBE.DETALLEPEDIDO (IDPEDIDO,IDARTICULO,CANTIDAD,PREVENTA,SUBTOTAL) values ('8','P0003   ','1','0','20');
Insert into CEURIBE.DETALLEPEDIDO (IDPEDIDO,IDARTICULO,CANTIDAD,PREVENTA,SUBTOTAL) values ('8','P0004   ','1','0','8,9');
Insert into CEURIBE.DETALLEPEDIDO (IDPEDIDO,IDARTICULO,CANTIDAD,PREVENTA,SUBTOTAL) values ('8','P0006   ','1','0','4,9');
Insert into CEURIBE.DETALLEPEDIDO (IDPEDIDO,IDARTICULO,CANTIDAD,PREVENTA,SUBTOTAL) values ('9','P0003   ','1','0','20');
Insert into CEURIBE.DETALLEPEDIDO (IDPEDIDO,IDARTICULO,CANTIDAD,PREVENTA,SUBTOTAL) values ('9','P0004   ','1','0','8,9');
Insert into CEURIBE.DETALLEPEDIDO (IDPEDIDO,IDARTICULO,CANTIDAD,PREVENTA,SUBTOTAL) values ('9','P0006   ','1','0','4,9');
Insert into CEURIBE.DETALLEPEDIDO (IDPEDIDO,IDARTICULO,CANTIDAD,PREVENTA,SUBTOTAL) values ('10','P0005   ','1','0','20');
Insert into CEURIBE.DETALLEPEDIDO (IDPEDIDO,IDARTICULO,CANTIDAD,PREVENTA,SUBTOTAL) values ('10','P0007   ','1','0','8,9');
Insert into CEURIBE.DETALLEPEDIDO (IDPEDIDO,IDARTICULO,CANTIDAD,PREVENTA,SUBTOTAL) values ('10','P0002   ','1','0','4,9');
Insert into CEURIBE.DETALLEPEDIDO (IDPEDIDO,IDARTICULO,CANTIDAD,PREVENTA,SUBTOTAL) values ('11','P0015   ','1','0','20');
Insert into CEURIBE.DETALLEPEDIDO (IDPEDIDO,IDARTICULO,CANTIDAD,PREVENTA,SUBTOTAL) values ('11','P0011   ','1','0','8,9');
Insert into CEURIBE.DETALLEPEDIDO (IDPEDIDO,IDARTICULO,CANTIDAD,PREVENTA,SUBTOTAL) values ('11','P0012   ','1','0','4,9');
Insert into CEURIBE.DETALLEPEDIDO (IDPEDIDO,IDARTICULO,CANTIDAD,PREVENTA,SUBTOTAL) values ('12','P0010   ','1','0','20');
Insert into CEURIBE.DETALLEPEDIDO (IDPEDIDO,IDARTICULO,CANTIDAD,PREVENTA,SUBTOTAL) values ('12','P0013   ','1','0','8,9');
Insert into CEURIBE.DETALLEPEDIDO (IDPEDIDO,IDARTICULO,CANTIDAD,PREVENTA,SUBTOTAL) values ('12','P0014   ','1','0','4,9');
Insert into CEURIBE.DETALLEPEDIDO (IDPEDIDO,IDARTICULO,CANTIDAD,PREVENTA,SUBTOTAL) values ('13','P0007   ','1','0','20');
Insert into CEURIBE.DETALLEPEDIDO (IDPEDIDO,IDARTICULO,CANTIDAD,PREVENTA,SUBTOTAL) values ('13','P0013   ','1','0','8,9');
Insert into CEURIBE.DETALLEPEDIDO (IDPEDIDO,IDARTICULO,CANTIDAD,PREVENTA,SUBTOTAL) values ('13','P0014   ','1','0','4,9');
Insert into CEURIBE.DETALLEPEDIDO (IDPEDIDO,IDARTICULO,CANTIDAD,PREVENTA,SUBTOTAL) values ('14','P0007   ','1','0','20');
Insert into CEURIBE.DETALLEPEDIDO (IDPEDIDO,IDARTICULO,CANTIDAD,PREVENTA,SUBTOTAL) values ('14','P0014   ','1','0','8,9');
Insert into CEURIBE.DETALLEPEDIDO (IDPEDIDO,IDARTICULO,CANTIDAD,PREVENTA,SUBTOTAL) values ('14','P0012   ','1','0','4,9');
Insert into CEURIBE.DETALLEPEDIDO (IDPEDIDO,IDARTICULO,CANTIDAD,PREVENTA,SUBTOTAL) values ('15','P0007   ','1','0','20');
Insert into CEURIBE.DETALLEPEDIDO (IDPEDIDO,IDARTICULO,CANTIDAD,PREVENTA,SUBTOTAL) values ('15','P0012   ','1','0','8,9');
Insert into CEURIBE.DETALLEPEDIDO (IDPEDIDO,IDARTICULO,CANTIDAD,PREVENTA,SUBTOTAL) values ('15','P0010   ','1','0','4,9');
Insert into CEURIBE.DETALLEPEDIDO (IDPEDIDO,IDARTICULO,CANTIDAD,PREVENTA,SUBTOTAL) values ('16','P0007   ','1','0','20');
Insert into CEURIBE.DETALLEPEDIDO (IDPEDIDO,IDARTICULO,CANTIDAD,PREVENTA,SUBTOTAL) values ('16','P0002   ','1','0','8,9');
Insert into CEURIBE.DETALLEPEDIDO (IDPEDIDO,IDARTICULO,CANTIDAD,PREVENTA,SUBTOTAL) values ('16','P0001   ','1','0','4,9');
Insert into CEURIBE.DETALLEPEDIDO (IDPEDIDO,IDARTICULO,CANTIDAD,PREVENTA,SUBTOTAL) values ('17','P0007   ','1','0','20');
Insert into CEURIBE.DETALLEPEDIDO (IDPEDIDO,IDARTICULO,CANTIDAD,PREVENTA,SUBTOTAL) values ('17','P0002   ','1','0','8,9');
Insert into CEURIBE.DETALLEPEDIDO (IDPEDIDO,IDARTICULO,CANTIDAD,PREVENTA,SUBTOTAL) values ('17','P0001   ','1','0','4,9');
Insert into CEURIBE.DETALLEPEDIDO (IDPEDIDO,IDARTICULO,CANTIDAD,PREVENTA,SUBTOTAL) values ('18','P0001   ','1','0','2,34');
Insert into CEURIBE.DETALLEPEDIDO (IDPEDIDO,IDARTICULO,CANTIDAD,PREVENTA,SUBTOTAL) values ('18','P0002   ','1','0','6,45');
Insert into CEURIBE.DETALLEPEDIDO (IDPEDIDO,IDARTICULO,CANTIDAD,PREVENTA,SUBTOTAL) values ('18','P0003   ','1','0','5,3');
Insert into CEURIBE.DETALLEPEDIDO (IDPEDIDO,IDARTICULO,CANTIDAD,PREVENTA,SUBTOTAL) values ('19','P0017   ','1','0','20');
Insert into CEURIBE.DETALLEPEDIDO (IDPEDIDO,IDARTICULO,CANTIDAD,PREVENTA,SUBTOTAL) values ('19','P0012   ','1','0','8,9');
Insert into CEURIBE.DETALLEPEDIDO (IDPEDIDO,IDARTICULO,CANTIDAD,PREVENTA,SUBTOTAL) values ('19','P0011   ','1','0','4,9');
Insert into CEURIBE.DETALLEPEDIDO (IDPEDIDO,IDARTICULO,CANTIDAD,PREVENTA,SUBTOTAL) values ('20','P0009   ','1','0','20');
Insert into CEURIBE.DETALLEPEDIDO (IDPEDIDO,IDARTICULO,CANTIDAD,PREVENTA,SUBTOTAL) values ('20','P0008   ','1','0','8,9');
Insert into CEURIBE.DETALLEPEDIDO (IDPEDIDO,IDARTICULO,CANTIDAD,PREVENTA,SUBTOTAL) values ('20','P0011   ','1','0','4,9');
Insert into CEURIBE.DETALLEPEDIDO (IDPEDIDO,IDARTICULO,CANTIDAD,PREVENTA,SUBTOTAL) values ('40','P0009   ','1','0','20');
Insert into CEURIBE.DETALLEPEDIDO (IDPEDIDO,IDARTICULO,CANTIDAD,PREVENTA,SUBTOTAL) values ('40','P0008   ','1','0','8,9');
Insert into CEURIBE.DETALLEPEDIDO (IDPEDIDO,IDARTICULO,CANTIDAD,PREVENTA,SUBTOTAL) values ('40','P0011   ','1','0','4,9');
Insert into CEURIBE.DETALLEPEDIDO (IDPEDIDO,IDARTICULO,CANTIDAD,PREVENTA,SUBTOTAL) values ('60','P0001   ','1','0','2,34');
Insert into CEURIBE.DETALLEPEDIDO (IDPEDIDO,IDARTICULO,CANTIDAD,PREVENTA,SUBTOTAL) values ('60','P0002   ','1','0','6,45');
Insert into CEURIBE.DETALLEPEDIDO (IDPEDIDO,IDARTICULO,CANTIDAD,PREVENTA,SUBTOTAL) values ('60','P0003   ','1','0','5,3');
REM INSERTING into CEURIBE.DOCUMENTO
SET DEFINE OFF;
Insert into CEURIBE.DOCUMENTO (IDDOCUMENTO,NOMDOCUMENTO,SERIE,CONDOCUMENTO) values ('1','Boleta','1','31');
Insert into CEURIBE.DOCUMENTO (IDDOCUMENTO,NOMDOCUMENTO,SERIE,CONDOCUMENTO) values ('2','Factura','1','31');
REM INSERTING into CEURIBE.EMPLEADO
SET DEFINE OFF;
Insert into CEURIBE.EMPLEADO (IDEMPLEADO,APEEMPLEADO,NOMEMPLEADO,DIREMPLEADO,TELEMPLEADO,CLAVE) values ('E00001','Paredes Rodriguez','Maria','Lince','430-1222','java1');
Insert into CEURIBE.EMPLEADO (IDEMPLEADO,APEEMPLEADO,NOMEMPLEADO,DIREMPLEADO,TELEMPLEADO,CLAVE) values ('E00002','Peña Olguín','Karol','Los Olivos','456-5999','java');
Insert into CEURIBE.EMPLEADO (IDEMPLEADO,APEEMPLEADO,NOMEMPLEADO,DIREMPLEADO,TELEMPLEADO,CLAVE) values ('E00003','Rojas Rojas','Armando','Rimac','459-4326','java');
Insert into CEURIBE.EMPLEADO (IDEMPLEADO,APEEMPLEADO,NOMEMPLEADO,DIREMPLEADO,TELEMPLEADO,CLAVE) values ('E00004','Manrique Tenorio','Maria','Miraflores','843-3519','java');
Insert into CEURIBE.EMPLEADO (IDEMPLEADO,APEEMPLEADO,NOMEMPLEADO,DIREMPLEADO,TELEMPLEADO,CLAVE) values ('E00005','Pazos Saavedra','Juan','Lince','870-3519','java');
Insert into CEURIBE.EMPLEADO (IDEMPLEADO,APEEMPLEADO,NOMEMPLEADO,DIREMPLEADO,TELEMPLEADO,CLAVE) values ('E00006','Vega Chávez','Karla','Rimac','None','java');
REM INSERTING into CEURIBE.ESTADO
SET DEFINE OFF;
Insert into CEURIBE.ESTADO (IDESTADO,DESESTADO) values ('1','ATENDIDO');
Insert into CEURIBE.ESTADO (IDESTADO,DESESTADO) values ('2','CANCELADO');
Insert into CEURIBE.ESTADO (IDESTADO,DESESTADO) values ('3','RECHAZADO');
REM INSERTING into CEURIBE.PARAMETRO
SET DEFINE OFF;
Insert into CEURIBE.PARAMETRO (CAMPO,VALOR) values ('Delivery','10.0');
Insert into CEURIBE.PARAMETRO (CAMPO,VALOR) values ('IGV','0.19');
Insert into CEURIBE.PARAMETRO (CAMPO,VALOR) values ('Empleado','6');
Insert into CEURIBE.PARAMETRO (CAMPO,VALOR) values ('Pedido','60');
Insert into CEURIBE.PARAMETRO (CAMPO,VALOR) values ('Cliente','10');
REM INSERTING into CEURIBE.PEDIDO
SET DEFINE OFF;
Insert into CEURIBE.PEDIDO (IDPEDIDO,IDDOCUMENTO,IDEMPLEADO,NUMDOCUMENTO,FECHA,IDCLIENTE,NOMCLIENTE,IMPORTE,DESCUENTO,SUBTOTAL,IGV,TOTAL,DELIVERY,ESTADO) values ('1','1','E00001','001-000001',to_date('20/08/05','DD/MM/RR'),'C00002','Pedro','50','0','50','9','59','1','1');
Insert into CEURIBE.PEDIDO (IDPEDIDO,IDDOCUMENTO,IDEMPLEADO,NUMDOCUMENTO,FECHA,IDCLIENTE,NOMCLIENTE,IMPORTE,DESCUENTO,SUBTOTAL,IGV,TOTAL,DELIVERY,ESTADO) values ('2','2','E00001','001-000001',to_date('20/08/05','DD/MM/RR'),'C00002',null,'80','0','80','14,4','94,4','1','1');
Insert into CEURIBE.PEDIDO (IDPEDIDO,IDDOCUMENTO,IDEMPLEADO,NUMDOCUMENTO,FECHA,IDCLIENTE,NOMCLIENTE,IMPORTE,DESCUENTO,SUBTOTAL,IGV,TOTAL,DELIVERY,ESTADO) values ('3','1','E00002','001-000002',to_date('20/08/06','DD/MM/RR'),'C00008','Magaly','100','0','100','18','118','5','1');
Insert into CEURIBE.PEDIDO (IDPEDIDO,IDDOCUMENTO,IDEMPLEADO,NUMDOCUMENTO,FECHA,IDCLIENTE,NOMCLIENTE,IMPORTE,DESCUENTO,SUBTOTAL,IGV,TOTAL,DELIVERY,ESTADO) values ('4','2','E00002','001-000002',to_date('20/08/06','DD/MM/RR'),'C00008',null,'90','0','90','16,2','106,2','5','1');
Insert into CEURIBE.PEDIDO (IDPEDIDO,IDDOCUMENTO,IDEMPLEADO,NUMDOCUMENTO,FECHA,IDCLIENTE,NOMCLIENTE,IMPORTE,DESCUENTO,SUBTOTAL,IGV,TOTAL,DELIVERY,ESTADO) values ('5','1','E00003','001-000003',to_date('20/08/07','DD/MM/RR'),'C00004','Doris','200','0','200','36','236','1','1');
Insert into CEURIBE.PEDIDO (IDPEDIDO,IDDOCUMENTO,IDEMPLEADO,NUMDOCUMENTO,FECHA,IDCLIENTE,NOMCLIENTE,IMPORTE,DESCUENTO,SUBTOTAL,IGV,TOTAL,DELIVERY,ESTADO) values ('6','2','E00003','001-000003',to_date('20/08/07','DD/MM/RR'),'C00004',null,'300','0','300','54','354','1','1');
Insert into CEURIBE.PEDIDO (IDPEDIDO,IDDOCUMENTO,IDEMPLEADO,NUMDOCUMENTO,FECHA,IDCLIENTE,NOMCLIENTE,IMPORTE,DESCUENTO,SUBTOTAL,IGV,TOTAL,DELIVERY,ESTADO) values ('7','1','E00004','001-000004',to_date('20/08/08','DD/MM/RR'),'C00005','Claudia','100','0','100','18','118','1','1');
Insert into CEURIBE.PEDIDO (IDPEDIDO,IDDOCUMENTO,IDEMPLEADO,NUMDOCUMENTO,FECHA,IDCLIENTE,NOMCLIENTE,IMPORTE,DESCUENTO,SUBTOTAL,IGV,TOTAL,DELIVERY,ESTADO) values ('8','2','E00004','001-000004',to_date('20/08/08','DD/MM/RR'),'C00005',null,'90','0','90','16,2','106,2','1','1');
Insert into CEURIBE.PEDIDO (IDPEDIDO,IDDOCUMENTO,IDEMPLEADO,NUMDOCUMENTO,FECHA,IDCLIENTE,NOMCLIENTE,IMPORTE,DESCUENTO,SUBTOTAL,IGV,TOTAL,DELIVERY,ESTADO) values ('9','1','E00005','001-000005',to_date('20/08/09','DD/MM/RR'),'C00004','Patricia','150','0','150','27','177','1','1');
Insert into CEURIBE.PEDIDO (IDPEDIDO,IDDOCUMENTO,IDEMPLEADO,NUMDOCUMENTO,FECHA,IDCLIENTE,NOMCLIENTE,IMPORTE,DESCUENTO,SUBTOTAL,IGV,TOTAL,DELIVERY,ESTADO) values ('10','2','E00005','001-000005',to_date('20/08/09','DD/MM/RR'),'C00004',null,'90','0','90','16,2','106,2','1','1');
Insert into CEURIBE.PEDIDO (IDPEDIDO,IDDOCUMENTO,IDEMPLEADO,NUMDOCUMENTO,FECHA,IDCLIENTE,NOMCLIENTE,IMPORTE,DESCUENTO,SUBTOTAL,IGV,TOTAL,DELIVERY,ESTADO) values ('11','1','E00006','001-000006',to_date('20/08/10','DD/MM/RR'),'C00007','Edgard','100','0','100','18','118','1','1');
Insert into CEURIBE.PEDIDO (IDPEDIDO,IDDOCUMENTO,IDEMPLEADO,NUMDOCUMENTO,FECHA,IDCLIENTE,NOMCLIENTE,IMPORTE,DESCUENTO,SUBTOTAL,IGV,TOTAL,DELIVERY,ESTADO) values ('12','2','E00006','001-000006',to_date('20/08/10','DD/MM/RR'),'C00007',null,'166','0','166','29,88','195,88','1','1');
Insert into CEURIBE.PEDIDO (IDPEDIDO,IDDOCUMENTO,IDEMPLEADO,NUMDOCUMENTO,FECHA,IDCLIENTE,NOMCLIENTE,IMPORTE,DESCUENTO,SUBTOTAL,IGV,TOTAL,DELIVERY,ESTADO) values ('13','1','E00001','001-000007',to_date('20/08/11','DD/MM/RR'),'C00008','Carlos','55','0','55','9,9','64,9','1','1');
Insert into CEURIBE.PEDIDO (IDPEDIDO,IDDOCUMENTO,IDEMPLEADO,NUMDOCUMENTO,FECHA,IDCLIENTE,NOMCLIENTE,IMPORTE,DESCUENTO,SUBTOTAL,IGV,TOTAL,DELIVERY,ESTADO) values ('14','2','E00001','001-000007',to_date('20/08/11','DD/MM/RR'),'C00008',null,'166','0','166','29,88','195,88','1','1');
Insert into CEURIBE.PEDIDO (IDPEDIDO,IDDOCUMENTO,IDEMPLEADO,NUMDOCUMENTO,FECHA,IDCLIENTE,NOMCLIENTE,IMPORTE,DESCUENTO,SUBTOTAL,IGV,TOTAL,DELIVERY,ESTADO) values ('15','1','E00002','001-000008',to_date('20/08/12','DD/MM/RR'),'C00004','César','55','0','55','9,9','64,9','5','1');
Insert into CEURIBE.PEDIDO (IDPEDIDO,IDDOCUMENTO,IDEMPLEADO,NUMDOCUMENTO,FECHA,IDCLIENTE,NOMCLIENTE,IMPORTE,DESCUENTO,SUBTOTAL,IGV,TOTAL,DELIVERY,ESTADO) values ('16','2','E00002','001-000008',to_date('20/08/12','DD/MM/RR'),'C00004',null,'120','0','120','21,6','141,6','1','1');
Insert into CEURIBE.PEDIDO (IDPEDIDO,IDDOCUMENTO,IDEMPLEADO,NUMDOCUMENTO,FECHA,IDCLIENTE,NOMCLIENTE,IMPORTE,DESCUENTO,SUBTOTAL,IGV,TOTAL,DELIVERY,ESTADO) values ('17','1','E00003','001-000009',to_date('20/08/13','DD/MM/RR'),'C00004','Manuel','144','0','144','25,92','169,92','1','1');
Insert into CEURIBE.PEDIDO (IDPEDIDO,IDDOCUMENTO,IDEMPLEADO,NUMDOCUMENTO,FECHA,IDCLIENTE,NOMCLIENTE,IMPORTE,DESCUENTO,SUBTOTAL,IGV,TOTAL,DELIVERY,ESTADO) values ('18','2','E00003','001-000009',to_date('20/08/13','DD/MM/RR'),'C00003',null,'120','0','120','21,6','141,6','1','1');
Insert into CEURIBE.PEDIDO (IDPEDIDO,IDDOCUMENTO,IDEMPLEADO,NUMDOCUMENTO,FECHA,IDCLIENTE,NOMCLIENTE,IMPORTE,DESCUENTO,SUBTOTAL,IGV,TOTAL,DELIVERY,ESTADO) values ('19','1','E00004','001-000010',to_date('20/08/14','DD/MM/RR'),'C00005','José','144','0','144','25,92','169,92','1','1');
Insert into CEURIBE.PEDIDO (IDPEDIDO,IDDOCUMENTO,IDEMPLEADO,NUMDOCUMENTO,FECHA,IDCLIENTE,NOMCLIENTE,IMPORTE,DESCUENTO,SUBTOTAL,IGV,TOTAL,DELIVERY,ESTADO) values ('20','2','E00004','001-000010',to_date('20/08/14','DD/MM/RR'),'C00005',null,'135','0','135','24,3','159,3','1','1');
Insert into CEURIBE.PEDIDO (IDPEDIDO,IDDOCUMENTO,IDEMPLEADO,NUMDOCUMENTO,FECHA,IDCLIENTE,NOMCLIENTE,IMPORTE,DESCUENTO,SUBTOTAL,IGV,TOTAL,DELIVERY,ESTADO) values ('40','2','E00004','001-000020',to_date('20/08/14','DD/MM/RR'),'C00005',null,'135','0','135','24,3','159,3','5','1');
Insert into CEURIBE.PEDIDO (IDPEDIDO,IDDOCUMENTO,IDEMPLEADO,NUMDOCUMENTO,FECHA,IDCLIENTE,NOMCLIENTE,IMPORTE,DESCUENTO,SUBTOTAL,IGV,TOTAL,DELIVERY,ESTADO) values ('60','2','E00004','001-000030',to_date('20/08/14','DD/MM/RR'),'C00005',null,'135','0','135','24,3','159,3','1','1');
REM INSERTING into CEURIBE.PRODUCTO
SET DEFINE OFF;
Insert into CEURIBE.PRODUCTO (CODIGO,NOMBRE,COSTO,STOCK) values ('P0004','Cojjnova','7,8','8');
Insert into CEURIBE.PRODUCTO (CODIGO,NOMBRE,COSTO,STOCK) values ('P0001','Cebolla Roja','2,34','10');
Insert into CEURIBE.PRODUCTO (CODIGO,NOMBRE,COSTO,STOCK) values ('P0002','Pollo','6,45','10');
Insert into CEURIBE.PRODUCTO (CODIGO,NOMBRE,COSTO,STOCK) values ('P0008','Arroz','4,9','9');
Insert into CEURIBE.PRODUCTO (CODIGO,NOMBRE,COSTO,STOCK) values ('P0011','Papa amarilla','5,6','7');
Insert into CEURIBE.PRODUCTO (CODIGO,NOMBRE,COSTO,STOCK) values ('P0012','Lentejas','4,6','9');
Insert into CEURIBE.PRODUCTO (CODIGO,NOMBRE,COSTO,STOCK) values ('P0003','Papa blanca','5,3','9');
Insert into CEURIBE.PRODUCTO (CODIGO,NOMBRE,COSTO,STOCK) values ('P0014','Frijol Canario','5,6','8');
Insert into CEURIBE.PRODUCTO (CODIGO,NOMBRE,COSTO,STOCK) values ('P0016','Lenguado','20','5');
Insert into CEURIBE.PRODUCTO (CODIGO,NOMBRE,COSTO,STOCK) values ('P0017','Sardina','8,9','10');
Insert into CEURIBE.PRODUCTO (CODIGO,NOMBRE,COSTO,STOCK) values ('P0018','Zanahoria','4,3','8');
Insert into CEURIBE.PRODUCTO (CODIGO,NOMBRE,COSTO,STOCK) values ('P0019','Quinua','8','10');
Insert into CEURIBE.PRODUCTO (CODIGO,NOMBRE,COSTO,STOCK) values ('P0020','Trigo','4,4','9');
Insert into CEURIBE.PRODUCTO (CODIGO,NOMBRE,COSTO,STOCK) values ('P0010','Mariscos','45,34','34');
Insert into CEURIBE.PRODUCTO (CODIGO,NOMBRE,COSTO,STOCK) values ('P0006','Tomates','3,4','33');
Insert into CEURIBE.PRODUCTO (CODIGO,NOMBRE,COSTO,STOCK) values ('P0007','Langostinos','34,34','12');
Insert into CEURIBE.PRODUCTO (CODIGO,NOMBRE,COSTO,STOCK) values ('P0015','Fideo Tallarin','4,3','10');
Insert into CEURIBE.PRODUCTO (CODIGO,NOMBRE,COSTO,STOCK) values ('P0005','Lomo Fino','34,56','233');
REM INSERTING into CEURIBE.PROMOCION
SET DEFINE OFF;
Insert into CEURIBE.PROMOCION (IDPROMOCION,MONTOMIN,MONTOMAX,PORCENTAJE) values ('1','0,1','30','0');
Insert into CEURIBE.PROMOCION (IDPROMOCION,MONTOMIN,MONTOMAX,PORCENTAJE) values ('2','30,1','50','2');
Insert into CEURIBE.PROMOCION (IDPROMOCION,MONTOMIN,MONTOMAX,PORCENTAJE) values ('3','50,1','100','4');
Insert into CEURIBE.PROMOCION (IDPROMOCION,MONTOMIN,MONTOMAX,PORCENTAJE) values ('4','100,1','500','6');
Insert into CEURIBE.PROMOCION (IDPROMOCION,MONTOMIN,MONTOMAX,PORCENTAJE) values ('5','500,1','1000','8');
Insert into CEURIBE.PROMOCION (IDPROMOCION,MONTOMIN,MONTOMAX,PORCENTAJE) values ('6','1000,1','10000','10');
REM INSERTING into CEURIBE.RESPUESTA
SET DEFINE OFF;
Insert into CEURIBE.RESPUESTA (ID,CODIGO,OPINION,COMENTARIO) values ('3','P0001','Mala',' fevevdf fd');
Insert into CEURIBE.RESPUESTA (ID,CODIGO,OPINION,COMENTARIO) values ('4','P0001','Buena',' fevevdf fddcedede');
Insert into CEURIBE.RESPUESTA (ID,CODIGO,OPINION,COMENTARIO) values ('5','P0001','Regular',' fevevdf fddcedede33333');
Insert into CEURIBE.RESPUESTA (ID,CODIGO,OPINION,COMENTARIO) values ('6','P0001','Regular','awef wefwefewf ');
Insert into CEURIBE.RESPUESTA (ID,CODIGO,OPINION,COMENTARIO) values ('1','P0001','Mala','e fgerf reer');
Insert into CEURIBE.RESPUESTA (ID,CODIGO,OPINION,COMENTARIO) values ('2','P0001','Buena',' fevevdf fd');
REM INSERTING into CEURIBE.USUARIO
SET DEFINE OFF;
Insert into CEURIBE.USUARIO (CODIGO,NOMBRES,APELLIDOS) values ('P0001','Carlos','Euribe');
Insert into CEURIBE.USUARIO (CODIGO,NOMBRES,APELLIDOS) values ('P0002','Luis','Lopez');
Insert into CEURIBE.USUARIO (CODIGO,NOMBRES,APELLIDOS) values ('P0003','Juana','Cardenas');
Insert into CEURIBE.USUARIO (CODIGO,NOMBRES,APELLIDOS) values ('P0004','Pedro','Diaz');
REM INSERTING into CEURIBE.VW_LISTARPRODUCTOS
SET DEFINE OFF;
Insert into CEURIBE.VW_LISTARPRODUCTOS (CODIGO,NOMBRE,COSTO,STOCK) values ('P0004','Cojjnova','7,8','8');
Insert into CEURIBE.VW_LISTARPRODUCTOS (CODIGO,NOMBRE,COSTO,STOCK) values ('P0001','Cebolla Roja','2,34','10');
Insert into CEURIBE.VW_LISTARPRODUCTOS (CODIGO,NOMBRE,COSTO,STOCK) values ('P0002','Pollo','6,45','10');
Insert into CEURIBE.VW_LISTARPRODUCTOS (CODIGO,NOMBRE,COSTO,STOCK) values ('P0008','Arroz','4,9','9');
Insert into CEURIBE.VW_LISTARPRODUCTOS (CODIGO,NOMBRE,COSTO,STOCK) values ('P0011','Papa amarilla','5,6','7');
Insert into CEURIBE.VW_LISTARPRODUCTOS (CODIGO,NOMBRE,COSTO,STOCK) values ('P0012','Lentejas','4,6','9');
Insert into CEURIBE.VW_LISTARPRODUCTOS (CODIGO,NOMBRE,COSTO,STOCK) values ('P0003','Papa blanca','5,3','9');
Insert into CEURIBE.VW_LISTARPRODUCTOS (CODIGO,NOMBRE,COSTO,STOCK) values ('P0014','Frijol Canario','5,6','8');
Insert into CEURIBE.VW_LISTARPRODUCTOS (CODIGO,NOMBRE,COSTO,STOCK) values ('P0016','Lenguado','20','5');
Insert into CEURIBE.VW_LISTARPRODUCTOS (CODIGO,NOMBRE,COSTO,STOCK) values ('P0017','Sardina','8,9','10');
Insert into CEURIBE.VW_LISTARPRODUCTOS (CODIGO,NOMBRE,COSTO,STOCK) values ('P0018','Zanahoria','4,3','8');
Insert into CEURIBE.VW_LISTARPRODUCTOS (CODIGO,NOMBRE,COSTO,STOCK) values ('P0019','Quinua','8','10');
Insert into CEURIBE.VW_LISTARPRODUCTOS (CODIGO,NOMBRE,COSTO,STOCK) values ('P0020','Trigo','4,4','9');
Insert into CEURIBE.VW_LISTARPRODUCTOS (CODIGO,NOMBRE,COSTO,STOCK) values ('P0010','Mariscos','45,34','34');
Insert into CEURIBE.VW_LISTARPRODUCTOS (CODIGO,NOMBRE,COSTO,STOCK) values ('P0006','Tomates','3,4','33');
Insert into CEURIBE.VW_LISTARPRODUCTOS (CODIGO,NOMBRE,COSTO,STOCK) values ('P0007','Langostinos','34,34','12');
Insert into CEURIBE.VW_LISTARPRODUCTOS (CODIGO,NOMBRE,COSTO,STOCK) values ('P0015','Fideo Tallarin','4,3','10');
Insert into CEURIBE.VW_LISTARPRODUCTOS (CODIGO,NOMBRE,COSTO,STOCK) values ('P0005','Lomo Fino','34,56','233');
--------------------------------------------------------
--  DDL for Index PKARTICULO
--------------------------------------------------------

  CREATE UNIQUE INDEX "CEURIBE"."PKARTICULO" ON "CEURIBE"."ARTICULO" ("IDARTICULO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PKCATEGORIA
--------------------------------------------------------

  CREATE UNIQUE INDEX "CEURIBE"."PKCATEGORIA" ON "CEURIBE"."CATEGORIA" ("IDCATEGORIA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PKCLIENTE
--------------------------------------------------------

  CREATE UNIQUE INDEX "CEURIBE"."PKCLIENTE" ON "CEURIBE"."CLIENTE" ("IDCLIENTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PKDETALLEPEDIDO
--------------------------------------------------------

  CREATE UNIQUE INDEX "CEURIBE"."PKDETALLEPEDIDO" ON "CEURIBE"."DETALLEPEDIDO" ("IDPEDIDO", "IDARTICULO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PKDOCUMENTO
--------------------------------------------------------

  CREATE UNIQUE INDEX "CEURIBE"."PKDOCUMENTO" ON "CEURIBE"."DOCUMENTO" ("IDDOCUMENTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PKEMPLEADO
--------------------------------------------------------

  CREATE UNIQUE INDEX "CEURIBE"."PKEMPLEADO" ON "CEURIBE"."EMPLEADO" ("IDEMPLEADO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PKPARAMETRO
--------------------------------------------------------

  CREATE UNIQUE INDEX "CEURIBE"."PKPARAMETRO" ON "CEURIBE"."PARAMETRO" ("CAMPO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PKPEDIDO
--------------------------------------------------------

  CREATE UNIQUE INDEX "CEURIBE"."PKPEDIDO" ON "CEURIBE"."PEDIDO" ("IDPEDIDO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PKPROMOCION
--------------------------------------------------------

  CREATE UNIQUE INDEX "CEURIBE"."PKPROMOCION" ON "CEURIBE"."PROMOCION" ("IDPROMOCION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PKRESPUESTA
--------------------------------------------------------

  CREATE UNIQUE INDEX "CEURIBE"."PKRESPUESTA" ON "CEURIBE"."RESPUESTA" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PKUSUARIO
--------------------------------------------------------

  CREATE UNIQUE INDEX "CEURIBE"."PKUSUARIO" ON "CEURIBE"."USUARIO" ("CODIGO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C004066
--------------------------------------------------------

  CREATE UNIQUE INDEX "CEURIBE"."SYS_C004066" ON "CEURIBE"."CATEGORIA" ("PREFIJO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C004139
--------------------------------------------------------

  CREATE UNIQUE INDEX "CEURIBE"."SYS_C004139" ON "CEURIBE"."ESTADO" ("IDESTADO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C004140
--------------------------------------------------------

  CREATE UNIQUE INDEX "CEURIBE"."SYS_C004140" ON "CEURIBE"."DELIVERY" ("IDDELIVERY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table ARTICULO
--------------------------------------------------------

  ALTER TABLE "CEURIBE"."ARTICULO" ADD CONSTRAINT "PKARTICULO" PRIMARY KEY ("IDARTICULO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "CEURIBE"."ARTICULO" MODIFY ("IDARTICULO" NOT NULL ENABLE);
 
  ALTER TABLE "CEURIBE"."ARTICULO" MODIFY ("IDCATEGORIA" NOT NULL ENABLE);
 
  ALTER TABLE "CEURIBE"."ARTICULO" MODIFY ("NOMARTICULO" NOT NULL ENABLE);
 
  ALTER TABLE "CEURIBE"."ARTICULO" MODIFY ("PREARTICULO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CATEGORIA
--------------------------------------------------------

  ALTER TABLE "CEURIBE"."CATEGORIA" ADD CONSTRAINT "PKCATEGORIA" PRIMARY KEY ("IDCATEGORIA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "CEURIBE"."CATEGORIA" MODIFY ("IDCATEGORIA" NOT NULL ENABLE);
 
  ALTER TABLE "CEURIBE"."CATEGORIA" MODIFY ("NOMCATEGORIA" NOT NULL ENABLE);
 
  ALTER TABLE "CEURIBE"."CATEGORIA" MODIFY ("PREFIJO" NOT NULL ENABLE);
 
  ALTER TABLE "CEURIBE"."CATEGORIA" MODIFY ("CONCATEGORIA" NOT NULL ENABLE);
 
  ALTER TABLE "CEURIBE"."CATEGORIA" ADD UNIQUE ("PREFIJO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CLIENTE
--------------------------------------------------------

  ALTER TABLE "CEURIBE"."CLIENTE" ADD CONSTRAINT "PKCLIENTE" PRIMARY KEY ("IDCLIENTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "CEURIBE"."CLIENTE" MODIFY ("IDCLIENTE" NOT NULL ENABLE);
 
  ALTER TABLE "CEURIBE"."CLIENTE" MODIFY ("NOMCLIENTE" NOT NULL ENABLE);
 
  ALTER TABLE "CEURIBE"."CLIENTE" MODIFY ("RUC" NOT NULL ENABLE);
 
  ALTER TABLE "CEURIBE"."CLIENTE" MODIFY ("DIRCLIENTE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DELIVERY
--------------------------------------------------------

  ALTER TABLE "CEURIBE"."DELIVERY" ADD PRIMARY KEY ("IDDELIVERY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DETALLEPEDIDO
--------------------------------------------------------

  ALTER TABLE "CEURIBE"."DETALLEPEDIDO" ADD CONSTRAINT "PKDETALLEPEDIDO" PRIMARY KEY ("IDPEDIDO", "IDARTICULO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "CEURIBE"."DETALLEPEDIDO" MODIFY ("IDPEDIDO" NOT NULL ENABLE);
 
  ALTER TABLE "CEURIBE"."DETALLEPEDIDO" MODIFY ("IDARTICULO" NOT NULL ENABLE);
 
  ALTER TABLE "CEURIBE"."DETALLEPEDIDO" MODIFY ("CANTIDAD" NOT NULL ENABLE);
 
  ALTER TABLE "CEURIBE"."DETALLEPEDIDO" MODIFY ("PREVENTA" NOT NULL ENABLE);
 
  ALTER TABLE "CEURIBE"."DETALLEPEDIDO" MODIFY ("SUBTOTAL" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DOCUMENTO
--------------------------------------------------------

  ALTER TABLE "CEURIBE"."DOCUMENTO" ADD CONSTRAINT "PKDOCUMENTO" PRIMARY KEY ("IDDOCUMENTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "CEURIBE"."DOCUMENTO" MODIFY ("IDDOCUMENTO" NOT NULL ENABLE);
 
  ALTER TABLE "CEURIBE"."DOCUMENTO" MODIFY ("SERIE" NOT NULL ENABLE);
 
  ALTER TABLE "CEURIBE"."DOCUMENTO" MODIFY ("CONDOCUMENTO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EMPLEADO
--------------------------------------------------------

  ALTER TABLE "CEURIBE"."EMPLEADO" ADD CONSTRAINT "PKEMPLEADO" PRIMARY KEY ("IDEMPLEADO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "CEURIBE"."EMPLEADO" MODIFY ("IDEMPLEADO" NOT NULL ENABLE);
 
  ALTER TABLE "CEURIBE"."EMPLEADO" MODIFY ("APEEMPLEADO" NOT NULL ENABLE);
 
  ALTER TABLE "CEURIBE"."EMPLEADO" MODIFY ("NOMEMPLEADO" NOT NULL ENABLE);
 
  ALTER TABLE "CEURIBE"."EMPLEADO" MODIFY ("CLAVE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ESTADO
--------------------------------------------------------

  ALTER TABLE "CEURIBE"."ESTADO" ADD PRIMARY KEY ("IDESTADO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PARAMETRO
--------------------------------------------------------

  ALTER TABLE "CEURIBE"."PARAMETRO" ADD CONSTRAINT "PKPARAMETRO" PRIMARY KEY ("CAMPO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "CEURIBE"."PARAMETRO" MODIFY ("CAMPO" NOT NULL ENABLE);
 
  ALTER TABLE "CEURIBE"."PARAMETRO" MODIFY ("VALOR" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PEDIDO
--------------------------------------------------------

  ALTER TABLE "CEURIBE"."PEDIDO" ADD CONSTRAINT "PKPEDIDO" PRIMARY KEY ("IDPEDIDO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "CEURIBE"."PEDIDO" MODIFY ("IDPEDIDO" NOT NULL ENABLE);
 
  ALTER TABLE "CEURIBE"."PEDIDO" MODIFY ("IDDOCUMENTO" NOT NULL ENABLE);
 
  ALTER TABLE "CEURIBE"."PEDIDO" MODIFY ("IDEMPLEADO" NOT NULL ENABLE);
 
  ALTER TABLE "CEURIBE"."PEDIDO" MODIFY ("NUMDOCUMENTO" NOT NULL ENABLE);
 
  ALTER TABLE "CEURIBE"."PEDIDO" MODIFY ("FECHA" NOT NULL ENABLE);
 
  ALTER TABLE "CEURIBE"."PEDIDO" MODIFY ("IMPORTE" NOT NULL ENABLE);
 
  ALTER TABLE "CEURIBE"."PEDIDO" MODIFY ("DESCUENTO" NOT NULL ENABLE);
 
  ALTER TABLE "CEURIBE"."PEDIDO" MODIFY ("SUBTOTAL" NOT NULL ENABLE);
 
  ALTER TABLE "CEURIBE"."PEDIDO" MODIFY ("IGV" NOT NULL ENABLE);
 
  ALTER TABLE "CEURIBE"."PEDIDO" MODIFY ("TOTAL" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PRODUCTO
--------------------------------------------------------

  ALTER TABLE "CEURIBE"."PRODUCTO" MODIFY ("CODIGO" NOT NULL ENABLE);
 
  ALTER TABLE "CEURIBE"."PRODUCTO" MODIFY ("NOMBRE" NOT NULL ENABLE);
 
  ALTER TABLE "CEURIBE"."PRODUCTO" MODIFY ("COSTO" NOT NULL ENABLE);
 
  ALTER TABLE "CEURIBE"."PRODUCTO" MODIFY ("STOCK" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PROMOCION
--------------------------------------------------------

  ALTER TABLE "CEURIBE"."PROMOCION" ADD CONSTRAINT "PKPROMOCION" PRIMARY KEY ("IDPROMOCION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "CEURIBE"."PROMOCION" MODIFY ("IDPROMOCION" NOT NULL ENABLE);
 
  ALTER TABLE "CEURIBE"."PROMOCION" MODIFY ("MONTOMIN" NOT NULL ENABLE);
 
  ALTER TABLE "CEURIBE"."PROMOCION" MODIFY ("MONTOMAX" NOT NULL ENABLE);
 
  ALTER TABLE "CEURIBE"."PROMOCION" MODIFY ("PORCENTAJE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RESPUESTA
--------------------------------------------------------

  ALTER TABLE "CEURIBE"."RESPUESTA" ADD CONSTRAINT "PKRESPUESTA" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "CEURIBE"."RESPUESTA" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "CEURIBE"."RESPUESTA" MODIFY ("CODIGO" NOT NULL ENABLE);
 
  ALTER TABLE "CEURIBE"."RESPUESTA" MODIFY ("OPINION" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table USUARIO
--------------------------------------------------------

  ALTER TABLE "CEURIBE"."USUARIO" ADD CONSTRAINT "PKUSUARIO" PRIMARY KEY ("CODIGO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "CEURIBE"."USUARIO" MODIFY ("CODIGO" NOT NULL ENABLE);
 
  ALTER TABLE "CEURIBE"."USUARIO" MODIFY ("NOMBRES" NOT NULL ENABLE);
 
  ALTER TABLE "CEURIBE"."USUARIO" MODIFY ("APELLIDOS" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table ARTICULO
--------------------------------------------------------

  ALTER TABLE "CEURIBE"."ARTICULO" ADD CONSTRAINT "FKARTICULOCATEGORIA" FOREIGN KEY ("IDCATEGORIA")
	  REFERENCES "CEURIBE"."CATEGORIA" ("IDCATEGORIA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DETALLEPEDIDO
--------------------------------------------------------

  ALTER TABLE "CEURIBE"."DETALLEPEDIDO" ADD CONSTRAINT "FKDETALLEPEDIDOPEDIDO" FOREIGN KEY ("IDPEDIDO")
	  REFERENCES "CEURIBE"."PEDIDO" ("IDPEDIDO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PEDIDO
--------------------------------------------------------

  ALTER TABLE "CEURIBE"."PEDIDO" ADD CONSTRAINT "FKPEDIDOCLIENTE" FOREIGN KEY ("IDCLIENTE")
	  REFERENCES "CEURIBE"."CLIENTE" ("IDCLIENTE") ENABLE;
 
  ALTER TABLE "CEURIBE"."PEDIDO" ADD CONSTRAINT "FKPEDIDODOCUMENTO" FOREIGN KEY ("IDDOCUMENTO")
	  REFERENCES "CEURIBE"."DOCUMENTO" ("IDDOCUMENTO") ENABLE;
 
  ALTER TABLE "CEURIBE"."PEDIDO" ADD CONSTRAINT "FKPEDIDOEMPLEADO" FOREIGN KEY ("IDEMPLEADO")
	  REFERENCES "CEURIBE"."EMPLEADO" ("IDEMPLEADO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RESPUESTA
--------------------------------------------------------

  ALTER TABLE "CEURIBE"."RESPUESTA" ADD CONSTRAINT "FKRESPUESTAUSUARIO" FOREIGN KEY ("CODIGO")
	  REFERENCES "CEURIBE"."USUARIO" ("CODIGO") ENABLE;
--------------------------------------------------------
--  DDL for Procedure SP_ACTUALIZARPRODUCTOS
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "CEURIBE"."SP_ACTUALIZARPRODUCTOS" (
  cCodigo PRODUCTO.CODIGO%TYPE, 
  vNombre PRODUCTO.NOMBRE%TYPE, 
  nCosto PRODUCTO.COSTO%TYPE, 
  nStock PRODUCTO.STOCK%TYPE,
  out_resultado OUT VARCHAR2)
IS
  BEGIN
    UPDATE PRODUCTO 
       SET NOMBRE = vNombre, 
           COSTO = nCosto, 
           STOCK = nStock 
    WHERE CODIGO = cCodigo;
    COMMIT;
    out_resultado := 'TRUE';
    EXCEPTION
      WHEN OTHERS THEN 
      out_resultado := 'FALSE';
      ROLLBACK;
  END;

/
--------------------------------------------------------
--  DDL for Procedure SP_BUSCARCODIGOUSUARIO
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "CEURIBE"."SP_BUSCARCODIGOUSUARIO" (
  cNombres USUARIO.NOMBRES%TYPE,
  cApellidos USUARIO.APELLIDOS%TYPE,
  cCodigo OUT VARCHAR2
  )
AS
  BEGIN
    SELECT codigo INTO cCodigo FROM USUARIO WHERE nombres LIKE cNombres||'%' and apellidos like cApellidos||'%';
    COMMIT;
  END;

/
--------------------------------------------------------
--  DDL for Procedure SP_ELIMINARCLIENTES
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "CEURIBE"."SP_ELIMINARCLIENTES" (
  cCodigo CLIENTE.IDCLIENTE%TYPE,
  out_resultado OUT VARCHAR2
  )
IS
  BEGIN
    DELETE FROM CLIENTE WHERE IDCLIENTE = cCodigo;
    COMMIT;
    out_resultado := 'TRUE';
    EXCEPTION
      WHEN OTHERS THEN 
      out_resultado := 'FALSE';
      ROLLBACK;
  END;

/
--------------------------------------------------------
--  DDL for Procedure SP_ELIMINARPRODUCTOS
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "CEURIBE"."SP_ELIMINARPRODUCTOS" (
  cCodigo PRODUCTO.CODIGO%TYPE,
  out_resultado OUT VARCHAR2
  )
IS
  BEGIN
    DELETE FROM PRODUCTO WHERE CODIGO = cCodigo;
    COMMIT;
    out_resultado := 'TRUE';
    EXCEPTION
      WHEN OTHERS THEN 
      out_resultado := 'FALSE';
      ROLLBACK;
  END;

/
--------------------------------------------------------
--  DDL for Procedure SP_ENTREGAPEDIDOS
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "CEURIBE"."SP_ENTREGAPEDIDOS" (
  cPedido PEDIDO.IDPEDIDO%TYPE, 
  out_resultado OUT VARCHAR2)
IS
  BEGIN
    UPDATE PEDIDO 
       SET DELIVERY = 5
    WHERE IDPEDIDO = cPedido;
    COMMIT;
    out_resultado := 'TRUE';
    EXCEPTION
      WHEN OTHERS THEN 
      out_resultado := 'FALSE';
      ROLLBACK;
  END;

/
--------------------------------------------------------
--  DDL for Procedure SP_INSERTARPRODUCTOS
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "CEURIBE"."SP_INSERTARPRODUCTOS" (
  cCodigo PRODUCTO.CODIGO%TYPE, 
  vNombre PRODUCTO.NOMBRE%TYPE, 
  nCosto PRODUCTO.COSTO%TYPE, 
  nStock PRODUCTO.STOCK%TYPE,
  out_resultado OUT VARCHAR2)
IS
  BEGIN
    INSERT INTO PRODUCTO (CODIGO, NOMBRE, COSTO, STOCK) VALUES(cCodigo, vNombre, nCosto, nStock);
    COMMIT;
    out_resultado := 'TRUE';
    EXCEPTION
      WHEN OTHERS THEN 
      out_resultado := 'FALSE';
      ROLLBACK;
  END;

/
--------------------------------------------------------
--  DDL for Procedure SP_INSERTARRESPUESTAS
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "CEURIBE"."SP_INSERTARRESPUESTAS" (
  iID RESPUESTA.ID%TYPE, 
  cCODIGO RESPUESTA.CODIGO%TYPE, 
  vOpinion RESPUESTA.OPINION%TYPE, 
  vComentario RESPUESTA.COMENTARIO%TYPE,
  out_resultado OUT VARCHAR2)
IS
  BEGIN
    INSERT INTO RESPUESTA (ID, CODIGO, OPINION, COMENTARIO) VALUES(iID, cCodigo, vOpinion, vComentario);
    COMMIT;
    out_resultado := 'TRUE';
    EXCEPTION
      WHEN OTHERS THEN 
      out_resultado := 'FALSE';
      ROLLBACK;
  END;

/
--------------------------------------------------------
--  DDL for Procedure SP_LISTARCLIENTES
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "CEURIBE"."SP_LISTARCLIENTES" (
  clientes OUT SYS_REFCURSOR
  )
AS
  BEGIN
    OPEN clientes FOR SELECT C.IDCLIENTE, C.NOMCLIENTE, C.RUC, C.DIRCLIENTE, C.TELCLIENTE, C.CLAVE, COUNT(P.IDPEDIDO) As NroPedidos, NVL(SUM(P.TOTAL),0) As TotalPedidos
                      FROM CLIENTE C
                      LEFT JOIN PEDIDO P ON C.IDCLIENTE = P.IDCLIENTE
                      GROUP BY C.IDCLIENTE, C.NOMCLIENTE, C.RUC, C.DIRCLIENTE, C.TELCLIENTE, C.CLAVE;
  END;

/
--------------------------------------------------------
--  DDL for Procedure SP_LISTARDETALLEXPEDIDO
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "CEURIBE"."SP_LISTARDETALLEXPEDIDO" (
  cPedido DETALLEPEDIDO.IDPEDIDO%TYPE,
  items OUT SYS_REFCURSOR
  )
AS
  BEGIN
    OPEN items FOR SELECT D.IDPEDIDO, D.IDARTICULO, A.NOMBRE, D.CANTIDAD, D.PREVENTA, D.SUBTOTAL
                      FROM DETALLEPEDIDO D
                      INNER JOIN PRODUCTO A ON D.IDARTICULO = A.CODIGO
                      WHERE D.IDPEDIDO = cPedido;
                      COMMIT;
  END;

/
--------------------------------------------------------
--  DDL for Procedure SP_LISTARPEDIDOSXCLIENTE
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "CEURIBE"."SP_LISTARPEDIDOSXCLIENTE" (
  cCliente PEDIDO.IDCLIENTE%TYPE,
  clientes OUT SYS_REFCURSOR
  )
AS
  BEGIN
    OPEN clientes FOR SELECT P.IDPEDIDO, P.NUMDOCUMENTO, P.FECHA, P.IMPORTE, P.DESCUENTO, P.SUBTOTAL, P.IGV, P.TOTAL, D.DESDELIVERY, ES.DESESTADO, E.NOMEMPLEADO, E.TELEMPLEADO
                      FROM PEDIDO P
                      INNER JOIN CLIENTE C ON C.IDCLIENTE = P.IDCLIENTE
                      INNER JOIN EMPLEADO E ON E.IDEMPLEADO = P.IDEMPLEADO
                      INNER JOIN ESTADO ES ON ES.IDESTADO = P.ESTADO
                      INNER JOIN DELIVERY D ON D.IDDELIVERY = P.DELIVERY
                      WHERE P.IDCLIENTE = cCliente;
                      COMMIT;
  END;

/
--------------------------------------------------------
--  DDL for Procedure SP_LISTARPEDIDOSXEMPLEADO
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "CEURIBE"."SP_LISTARPEDIDOSXEMPLEADO" (
  cEmpleado PEDIDO.IDEMPLEADO%TYPE,
  empleados OUT SYS_REFCURSOR
  )
AS
  BEGIN
    OPEN empleados FOR SELECT P.IDPEDIDO, P.NUMDOCUMENTO, P.FECHA, P.IMPORTE, P.DESCUENTO, P.SUBTOTAL, P.IGV, P.TOTAL, D.DESDELIVERY, ES.DESESTADO, C.NOMCLIENTE, C.DIRCLIENTE, C.TELCLIENTE
                      FROM PEDIDO P
                      INNER JOIN CLIENTE C ON C.IDCLIENTE = P.IDCLIENTE
                      INNER JOIN EMPLEADO E ON E.IDEMPLEADO = P.IDEMPLEADO
                      INNER JOIN ESTADO ES ON ES.IDESTADO = P.ESTADO
                      INNER JOIN DELIVERY D ON D.IDDELIVERY = P.DELIVERY
                      WHERE P.IDEMPLEADO = cEmpleado;
                      COMMIT;
  END;

/
--------------------------------------------------------
--  DDL for Procedure SP_LISTARPRODUCTOS
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "CEURIBE"."SP_LISTARPRODUCTOS" (
  productos OUT SYS_REFCURSOR
  )
AS
  BEGIN
    OPEN productos FOR SELECT CODIGO, NOMBRE, COSTO, STOCK FROM PRODUCTO;
  END;

/
--------------------------------------------------------
--  DDL for Procedure SP_TOTALRESPUESTAS
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "CEURIBE"."SP_TOTALRESPUESTAS" (
  total OUT INTEGER
  )
AS
  BEGIN
    SELECT COUNT(CODIGO) INTO total FROM RESPUESTA;
    COMMIT;
  END;

/
--------------------------------------------------------
--  DDL for Procedure SP_TRAERPRODUCTOS
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "CEURIBE"."SP_TRAERPRODUCTOS" (
  cCodigo PRODUCTO.CODIGO%TYPE,
  productos OUT SYS_REFCURSOR
  )
AS
  BEGIN
    OPEN productos FOR SELECT CODIGO, NOMBRE, COSTO, STOCK FROM PRODUCTO WHERE CODIGO = cCodigo;
  END;

/
--------------------------------------------------------
--  DDL for Procedure SP_VALIDARCLIENTE
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "CEURIBE"."SP_VALIDARCLIENTE" (
  cCodigo CLIENTE.IDCLIENTE%TYPE,
  cClave CLIENTE.CLAVE%TYPE,
  out_cliente OUT VARCHAR2)
IS
  iExiste INT;
  BEGIN
    
    SELECT COUNT(*) INTO iExiste FROM CLIENTE WHERE IDCLIENTE = cCodigo AND CLAVE = cClave;
    
    IF iExiste > 0 THEN
        out_cliente := 'TRUE';
    ELSE
        out_cliente := 'FALSE';
    END IF;
    
  END;

/
--------------------------------------------------------
--  DDL for Procedure SP_VALIDAREMPLEADO
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "CEURIBE"."SP_VALIDAREMPLEADO" (
  cCodigo EMPLEADO.IDEMPLEADO%TYPE,
  cClave EMPLEADO.CLAVE%TYPE,
  out_empleado OUT VARCHAR2)
IS
  iExiste INT;
  BEGIN
    
    SELECT COUNT(*) INTO iExiste FROM EMPLEADO WHERE IDEMPLEADO = cCodigo AND CLAVE = cClave;
    
    IF iExiste > 0 THEN
        out_empleado := 'TRUE';
    ELSE
        out_empleado := 'FALSE';
    END IF;
    
  END;

/
