-- ============================================
-- LIMPIEZA FORZADA - Elimina TODAS las tablas
-- ============================================

ALTER SESSION SET NLS_DATE_FORMAT = 'YYYY-MM-DD';

-- Deshabilitar restricciones de FK temporalmente
BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE ORDER_DETAILS DISABLE CONSTRAINT FK_ORDERDETAILS_ORDERS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE ORDER_DETAILS DISABLE CONSTRAINT FK_ORDERDETAILS_PRODUCTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE ORDERS DISABLE CONSTRAINT FK_ORDERS_CUSTOMERS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE ORDERS DISABLE CONSTRAINT FK_ORDERS_EMPLOYEES';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE ORDERS DISABLE CONSTRAINT FK_ORDERS_SHIPPERS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE PRODUCTS DISABLE CONSTRAINT FK_PRODUCTS_SUPPLIERS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE PRODUCTS DISABLE CONSTRAINT FK_PRODUCTS_CATEGORIES';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE EMPLOYEES DISABLE CONSTRAINT FK_EMPLOYEES_REPORTSTO';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- Eliminar tablas
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE ORDER_DETAILS';
  DBMS_OUTPUT.PUT_LINE('✓ ORDER_DETAILS eliminada');
EXCEPTION WHEN OTHERS THEN
  DBMS_OUTPUT.PUT_LINE('- ORDER_DETAILS no existía o error: ' || SQLERRM);
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE ORDERS';
  DBMS_OUTPUT.PUT_LINE('✓ ORDERS eliminada');
EXCEPTION WHEN OTHERS THEN
  DBMS_OUTPUT.PUT_LINE('- ORDERS no existía o error: ' || SQLERRM);
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE PRODUCTS';
  DBMS_OUTPUT.PUT_LINE('✓ PRODUCTS eliminada');
EXCEPTION WHEN OTHERS THEN
  DBMS_OUTPUT.PUT_LINE('- PRODUCTS no existía o error: ' || SQLERRM);
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE EMPLOYEES';
  DBMS_OUTPUT.PUT_LINE('✓ EMPLOYEES eliminada');
EXCEPTION WHEN OTHERS THEN
  DBMS_OUTPUT.PUT_LINE('- EMPLOYEES no existía o error: ' || SQLERRM);
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE CUSTOMERS';
  DBMS_OUTPUT.PUT_LINE('✓ CUSTOMERS eliminada');
EXCEPTION WHEN OTHERS THEN
  DBMS_OUTPUT.PUT_LINE('- CUSTOMERS no existía o error: ' || SQLERRM);
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE SHIPPERS';
  DBMS_OUTPUT.PUT_LINE('✓ SHIPPERS eliminada');
EXCEPTION WHEN OTHERS THEN
  DBMS_OUTPUT.PUT_LINE('- SHIPPERS no existía o error: ' || SQLERRM);
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE SUPPLIERS';
  DBMS_OUTPUT.PUT_LINE('✓ SUPPLIERS eliminada');
EXCEPTION WHEN OTHERS THEN
  DBMS_OUTPUT.PUT_LINE('- SUPPLIERS no existía o error: ' || SQLERRM);
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE CATEGORIES';
  DBMS_OUTPUT.PUT_LINE('✓ CATEGORIES eliminada');
EXCEPTION WHEN OTHERS THEN
  DBMS_OUTPUT.PUT_LINE('- CATEGORIES no existía o error: ' || SQLERRM);
END;
/

PROMPT ============================================
PROMPT LIMPIEZA COMPLETADA
PROMPT ============================================
