-- ============================================
-- NORTHWIND - DROP Y RECREAR TABLAS
-- Ejecutar conectado como NORTHWIND
-- ============================================

-- Eliminar tablas en orden inverso de dependencias
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE ORDER_DETAILS';
  DBMS_OUTPUT.PUT_LINE('Tabla ORDER_DETAILS eliminada');
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN RAISE; END IF;
    DBMS_OUTPUT.PUT_LINE('ORDER_DETAILS no existía');
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE ORDERS';
  DBMS_OUTPUT.PUT_LINE('Tabla ORDERS eliminada');
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN RAISE; END IF;
    DBMS_OUTPUT.PUT_LINE('ORDERS no existía');
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE PRODUCTS';
  DBMS_OUTPUT.PUT_LINE('Tabla PRODUCTS eliminada');
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN RAISE; END IF;
    DBMS_OUTPUT.PUT_LINE('PRODUCTS no existía');
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE EMPLOYEES';
  DBMS_OUTPUT.PUT_LINE('Tabla EMPLOYEES eliminada');
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN RAISE; END IF;
    DBMS_OUTPUT.PUT_LINE('EMPLOYEES no existía');
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE CUSTOMERS';
  DBMS_OUTPUT.PUT_LINE('Tabla CUSTOMERS eliminada');
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN RAISE; END IF;
    DBMS_OUTPUT.PUT_LINE('CUSTOMERS no existía');
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE SHIPPERS';
  DBMS_OUTPUT.PUT_LINE('Tabla SHIPPERS eliminada');
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN RAISE; END IF;
    DBMS_OUTPUT.PUT_LINE('SHIPPERS no existía');
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE SUPPLIERS';
  DBMS_OUTPUT.PUT_LINE('Tabla SUPPLIERS eliminada');
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN RAISE; END IF;
    DBMS_OUTPUT.PUT_LINE('SUPPLIERS no existía');
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE CATEGORIES';
  DBMS_OUTPUT.PUT_LINE('Tabla CATEGORIES eliminada');
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN RAISE; END IF;
    DBMS_OUTPUT.PUT_LINE('CATEGORIES no existía');
END;
/

PROMPT ============================================
PROMPT RECREANDO TABLAS...
PROMPT ============================================

CREATE TABLE CATEGORIES (
    CATEGORY_ID NUMBER(9) NOT NULL,
    CATEGORY_NAME VARCHAR2(15) NOT NULL,
    DESCRIPTION VARCHAR2(2000),
    PICTURE VARCHAR2(255),
    CONSTRAINT PK_CATEGORIES PRIMARY KEY (CATEGORY_ID)
);

CREATE TABLE CUSTOMERS (
    CUSTOMER_ID NUMBER(9) NOT NULL,
    CUSTOMER_CODE VARCHAR2(5) NOT NULL,
    COMPANY_NAME VARCHAR2(40) NOT NULL,
    CONTACT_NAME VARCHAR2(30),
    CONTACT_TITLE VARCHAR2(30),
    ADDRESS VARCHAR2(60),
    CITY VARCHAR2(15),
    REGION VARCHAR2(15),
    POSTAL_CODE VARCHAR2(10),
    COUNTRY VARCHAR2(15),
    PHONE VARCHAR2(24),
    FAX VARCHAR2(24),
    CONSTRAINT PK_CUSTOMERS PRIMARY KEY (CUSTOMER_ID)
);

CREATE TABLE EMPLOYEES (
    EMPLOYEE_ID NUMBER(9) NOT NULL,
    LASTNAME VARCHAR2(20) NOT NULL,
    FIRSTNAME VARCHAR2(10) NOT NULL,
    TITLE VARCHAR2(30),
    TITLE_OF_COURTESY VARCHAR2(25),
    BIRTHDATE DATE,
    HIREDATE DATE,
    ADDRESS VARCHAR2(60),
    CITY VARCHAR2(15),
    REGION VARCHAR2(15),
    POSTAL_CODE VARCHAR2(10),
    COUNTRY VARCHAR2(15),
    HOME_PHONE VARCHAR2(24),
    EXTENSION VARCHAR2(4),
    PHOTO VARCHAR2(255),
    NOTES VARCHAR2(2000),
    REPORTS_TO NUMBER(9),

    CONSTRAINT PK_EMPLOYEES PRIMARY KEY (EMPLOYEE_ID),
    CONSTRAINT FK_EMPLOYEES_REPORTSTO
        FOREIGN KEY (REPORTS_TO)
        REFERENCES EMPLOYEES (EMPLOYEE_ID)
);

CREATE TABLE SHIPPERS (
    SHIPPER_ID NUMBER(9) NOT NULL,
    COMPANY_NAME VARCHAR2(40) NOT NULL,
    PHONE VARCHAR2(24),

    CONSTRAINT PK_SHIPPERS PRIMARY KEY (SHIPPER_ID)
);

CREATE TABLE SUPPLIERS (
    SUPPLIER_ID NUMBER(9) NOT NULL,
    COMPANY_NAME VARCHAR2(40) NOT NULL,
    CONTACT_NAME VARCHAR2(30),
    CONTACT_TITLE VARCHAR2(30),
    ADDRESS VARCHAR2(60),
    CITY VARCHAR2(15),
    REGION VARCHAR2(15),
    POSTAL_CODE VARCHAR2(10),
    COUNTRY VARCHAR2(15),
    PHONE VARCHAR2(24),
    FAX VARCHAR2(24),
    HOMEPAGE VARCHAR2(2000),

    CONSTRAINT PK_SUPPLIERS PRIMARY KEY (SUPPLIER_ID)
);

CREATE TABLE PRODUCTS (
    PRODUCT_ID NUMBER(9) NOT NULL,
    PRODUCT_NAME VARCHAR2(40) NOT NULL,
    SUPPLIER_ID NUMBER(9),
    CATEGORY_ID NUMBER(9),
    QUANTITY_PER_UNIT VARCHAR2(20),
    UNIT_PRICE NUMBER(19,4),
    UNITS_IN_STOCK NUMBER(5),
    UNITS_ON_ORDER NUMBER(5),
    REORDER_LEVEL NUMBER(5),
    DISCONTINUED NUMBER(1) DEFAULT 0 NOT NULL,

    CONSTRAINT PK_PRODUCTS PRIMARY KEY (PRODUCT_ID),

    CONSTRAINT FK_PRODUCTS_SUPPLIERS
        FOREIGN KEY (SUPPLIER_ID)
        REFERENCES SUPPLIERS (SUPPLIER_ID),

    CONSTRAINT FK_PRODUCTS_CATEGORIES
        FOREIGN KEY (CATEGORY_ID)
        REFERENCES CATEGORIES (CATEGORY_ID)
);

CREATE TABLE ORDERS (
    ORDER_ID NUMBER(9) NOT NULL,
    CUSTOMER_ID NUMBER(9),
    EMPLOYEE_ID NUMBER(9),
    ORDER_DATE DATE,
    REQUIRED_DATE DATE,
    SHIPPED_DATE DATE,
    SHIP_VIA NUMBER(9),
    FREIGHT NUMBER(10,2) DEFAULT 0,
    SHIP_NAME VARCHAR2(40),
    SHIP_ADDRESS VARCHAR2(60),
    SHIP_CITY VARCHAR2(15),
    SHIP_REGION VARCHAR2(15),
    SHIP_POSTAL_CODE VARCHAR2(10),
    SHIP_COUNTRY VARCHAR2(15),

    CONSTRAINT PK_ORDERS PRIMARY KEY (ORDER_ID),

    CONSTRAINT FK_ORDERS_CUSTOMERS
        FOREIGN KEY (CUSTOMER_ID)
        REFERENCES CUSTOMERS (CUSTOMER_ID),

    CONSTRAINT FK_ORDERS_EMPLOYEES
        FOREIGN KEY (EMPLOYEE_ID)
        REFERENCES EMPLOYEES (EMPLOYEE_ID),

    CONSTRAINT FK_ORDERS_SHIPPERS
        FOREIGN KEY (SHIP_VIA)
        REFERENCES SHIPPERS (SHIPPER_ID)
);

CREATE TABLE ORDER_DETAILS (
    ORDER_ID NUMBER(9) NOT NULL,
    PRODUCT_ID NUMBER(9) NOT NULL,
    UNIT_PRICE NUMBER(19,4) DEFAULT 0 NOT NULL,
    QUANTITY NUMBER(5) DEFAULT 1 NOT NULL,
    DISCOUNT NUMBER(7,4) DEFAULT 0 NOT NULL,

    CONSTRAINT PK_ORDER_DETAILS
        PRIMARY KEY (ORDER_ID, PRODUCT_ID),

    CONSTRAINT FK_ORDERDETAILS_ORDERS
        FOREIGN KEY (ORDER_ID)
        REFERENCES ORDERS (ORDER_ID),

    CONSTRAINT FK_ORDERDETAILS_PRODUCTS
        FOREIGN KEY (PRODUCT_ID)
        REFERENCES PRODUCTS (PRODUCT_ID)
);

COMMIT;

PROMPT ============================================
PROMPT TABLAS NORTHWIND RECREADAS CORRECTAMENTE
PROMPT ============================================

SELECT TABLE_NAME
FROM USER_TABLES
ORDER BY TABLE_NAME;
