-- ============================================
-- NORTHWIND - CARGA DE DATOS SIMPLE
-- ============================================

-- CATEGORIES
INSERT INTO CATEGORIES (CATEGORY_ID, CATEGORY_NAME, DESCRIPTION, PICTURE)
VALUES (1, 'Beverages', 'Soft drinks, coffees, teas, beers, and ales', 'beverages.gif');
INSERT INTO CATEGORIES (CATEGORY_ID, CATEGORY_NAME, DESCRIPTION, PICTURE)
VALUES (2, 'Condiments', 'Sweet and savory sauces, relishes, spreads, and seasonings', 'condiments.gif');
INSERT INTO CATEGORIES (CATEGORY_ID, CATEGORY_NAME, DESCRIPTION, PICTURE)
VALUES (3, 'Confections', 'Desserts, candies, and sweet breads', 'confections.gif');
INSERT INTO CATEGORIES (CATEGORY_ID, CATEGORY_NAME, DESCRIPTION, PICTURE)
VALUES (4, 'Dairy Products', 'Cheeses', 'diary.gif');
INSERT INTO CATEGORIES (CATEGORY_ID, CATEGORY_NAME, DESCRIPTION, PICTURE)
VALUES (5, 'Grains/Cereals', 'Breads, crackers, pasta, and cereal', 'cereals.gif');
INSERT INTO CATEGORIES (CATEGORY_ID, CATEGORY_NAME, DESCRIPTION, PICTURE)
VALUES (6, 'Meat/Poultry', 'Prepared meats', 'meat.gif');
INSERT INTO CATEGORIES (CATEGORY_ID, CATEGORY_NAME, DESCRIPTION, PICTURE)
VALUES (7, 'Produce', 'Dried fruit and bean curd', 'produce.gif');
INSERT INTO CATEGORIES (CATEGORY_ID, CATEGORY_NAME, DESCRIPTION, PICTURE)
VALUES (8, 'Seafood', 'Seaweed and fish', 'seafood.gif');

-- SUPPLIERS
INSERT INTO SUPPLIERS (SUPPLIER_ID, COMPANY_NAME, CONTACT_NAME, CONTACT_TITLE, ADDRESS, CITY, REGION, POSTAL_CODE, COUNTRY, PHONE, FAX, HOMEPAGE)
VALUES (1, 'Exotic Liquids', 'Charlotte Cooper', 'Purchasing Manager', '49 Gilbert St.', 'London', NULL, 'EC1 4SD', 'UK', '(171) 555-2222', NULL, NULL);
INSERT INTO SUPPLIERS (SUPPLIER_ID, COMPANY_NAME, CONTACT_NAME, CONTACT_TITLE, ADDRESS, CITY, REGION, POSTAL_CODE, COUNTRY, PHONE, FAX, HOMEPAGE)
VALUES (2, 'New Orleans Cajun Delights', 'Shelley Burke', 'Order Administrator', 'P.O. Box 78934', 'New Orleans', 'LA', '70117', 'USA', '(100) 555-4822', NULL, NULL);
INSERT INTO SUPPLIERS (SUPPLIER_ID, COMPANY_NAME, CONTACT_NAME, CONTACT_TITLE, ADDRESS, CITY, REGION, POSTAL_CODE, COUNTRY, PHONE, FAX, HOMEPAGE)
VALUES (3, 'Grandma Kelly Homestead', 'Regina Murphy', 'Sales Representative', '707 Oxford Rd.', 'Ann Arbor', 'MI', '48104', 'USA', '(313) 555-5735', '(313) 555-3349', NULL);

-- SHIPPERS
INSERT INTO SHIPPERS (SHIPPER_ID, COMPANY_NAME, PHONE)
VALUES (1, 'Speedy Express', '(503) 555-9831');
INSERT INTO SHIPPERS (SHIPPER_ID, COMPANY_NAME, PHONE)
VALUES (2, 'United Package', '(503) 555-3199');
INSERT INTO SHIPPERS (SHIPPER_ID, COMPANY_NAME, PHONE)
VALUES (3, 'Federal Shipping', '(503) 555-9931');

-- EMPLOYEES
INSERT INTO EMPLOYEES (EMPLOYEE_ID, LASTNAME, FIRSTNAME, TITLE, TITLE_OF_COURTESY, BIRTHDATE, HIREDATE, ADDRESS, CITY, REGION, POSTAL_CODE, COUNTRY, HOME_PHONE, EXTENSION, PHOTO, NOTES, REPORTS_TO, PHOTOPATH)
VALUES (1, 'Davolio', 'Nancy', 'Sales Representative', 'Ms.', TO_DATE('1948-12-08', 'YYYY-MM-DD'), TO_DATE('1992-05-01', 'YYYY-MM-DD'), '507 - 20th Ave. E.', 'Seattle', 'WA', '98122', 'USA', '(206) 555-9857', '5467', NULL, 'Education includes a BA in psychology from Colorado State University in 1970. She also completed "The Art of the Cold Call." Nancy is a member of Toastmasters International.', NULL, NULL);
INSERT INTO EMPLOYEES (EMPLOYEE_ID, LASTNAME, FIRSTNAME, TITLE, TITLE_OF_COURTESY, BIRTHDATE, HIREDATE, ADDRESS, CITY, REGION, POSTAL_CODE, COUNTRY, HOME_PHONE, EXTENSION, PHOTO, NOTES, REPORTS_TO, PHOTOPATH)
VALUES (2, 'Fuller', 'Andrew', 'Vice President, Sales', 'Dr.', TO_DATE('1952-02-19', 'YYYY-MM-DD'), TO_DATE('1992-08-14', 'YYYY-MM-DD'), '908 W. Capital Way', 'Tacoma', 'WA', '98401', 'USA', '(206) 555-9482', '3457', NULL, 'Andrew received his BTS in C in 1974 and a Ph.D. in International Marketing from UCLA.', NULL, NULL);

-- CUSTOMERS
INSERT INTO CUSTOMERS (CUSTOMER_ID, CUSTOMER_CODE, COMPANY_NAME, CONTACT_NAME, CONTACT_TITLE, ADDRESS, CITY, REGION, POSTAL_CODE, COUNTRY, PHONE, FAX)
VALUES (1, 'ALFKI', 'Alfreds Futterkiste', 'Maria Anders', 'Sales Representative', 'Obere Str. 57', 'Berlin', NULL, '12209', 'Germany', '030-0074321', '030-0076545');
INSERT INTO CUSTOMERS (CUSTOMER_ID, CUSTOMER_CODE, COMPANY_NAME, CONTACT_NAME, CONTACT_TITLE, ADDRESS, CITY, REGION, POSTAL_CODE, COUNTRY, PHONE, FAX)
VALUES (2, 'ANATR', 'Ana Trujillo Emparedados y helados', 'Ana Trujillo', 'Owner', 'Avda. de la Constitucion 2222', 'Mexico D.F.', NULL, '05021', 'Mexico', '(5) 555-4729', '(5) 555-3745');
INSERT INTO CUSTOMERS (CUSTOMER_ID, CUSTOMER_CODE, COMPANY_NAME, CONTACT_NAME, CONTACT_TITLE, ADDRESS, CITY, REGION, POSTAL_CODE, COUNTRY, PHONE, FAX)
VALUES (3, 'ANTON', 'Antonio Moreno Taqueria', 'Antonio Moreno', 'Owner', 'Mataderos 2312', 'Mexico D.F.', NULL, '05023', 'Mexico', '(5) 555-3932', NULL);

-- PRODUCTS
INSERT INTO PRODUCTS (PRODUCT_ID, PRODUCT_NAME, SUPPLIER_ID, CATEGORY_ID, QUANTITY_PER_UNIT, UNIT_PRICE, UNITS_IN_STOCK, UNITS_ON_ORDER, REORDER_LEVEL, DISCONTINUED)
VALUES (1, 'Chai', 1, 1, '10 boxes x 20 bags', 18, 39, 0, 10, 'N');
INSERT INTO PRODUCTS (PRODUCT_ID, PRODUCT_NAME, SUPPLIER_ID, CATEGORY_ID, QUANTITY_PER_UNIT, UNIT_PRICE, UNITS_IN_STOCK, UNITS_ON_ORDER, REORDER_LEVEL, DISCONTINUED)
VALUES (2, 'Chang', 1, 1, '24 - 12 oz bottles', 19, 17, 40, 25, 'N');
INSERT INTO PRODUCTS (PRODUCT_ID, PRODUCT_NAME, SUPPLIER_ID, CATEGORY_ID, QUANTITY_PER_UNIT, UNIT_PRICE, UNITS_IN_STOCK, UNITS_ON_ORDER, REORDER_LEVEL, DISCONTINUED)
VALUES (3, 'Aniseed Syrup', 1, 2, '12 - 550 ml bottles', 10, 13, 70, 25, 'N');
INSERT INTO PRODUCTS (PRODUCT_ID, PRODUCT_NAME, SUPPLIER_ID, CATEGORY_ID, QUANTITY_PER_UNIT, UNIT_PRICE, UNITS_IN_STOCK, UNITS_ON_ORDER, REORDER_LEVEL, DISCONTINUED)
VALUES (4, 'Chef Anton Cajun Seasoning', 2, 2, '48 - 6 oz jars', 22, 53, 0, 0, 'N');
INSERT INTO PRODUCTS (PRODUCT_ID, PRODUCT_NAME, SUPPLIER_ID, CATEGORY_ID, QUANTITY_PER_UNIT, UNIT_PRICE, UNITS_IN_STOCK, UNITS_ON_ORDER, REORDER_LEVEL, DISCONTINUED)
VALUES (5, 'Chef Anton Gumbo Mix', 2, 2, '36 boxes', 21.35, 0, 0, 0, 'Y');

-- ORDERS
INSERT INTO ORDERS (ORDER_ID, CUSTOMER_ID, EMPLOYEE_ID, ORDER_DATE, REQUIRED_DATE, SHIPPED_DATE, SHIP_VIA, FREIGHT, SHIP_NAME, SHIP_ADDRESS, SHIP_CITY, SHIP_REGION, SHIP_POSTAL_CODE, SHIP_COUNTRY)
VALUES (10248, 1, 1, TO_DATE('1996-07-04', 'YYYY-MM-DD'), TO_DATE('1996-08-01', 'YYYY-MM-DD'), TO_DATE('1996-07-16', 'YYYY-MM-DD'), 3, 32.38, 'Vins et alcools Chevalier', '59 rue de l''Abbaye', 'Reims', NULL, '51100', 'France');
INSERT INTO ORDERS (ORDER_ID, CUSTOMER_ID, EMPLOYEE_ID, ORDER_DATE, REQUIRED_DATE, SHIPPED_DATE, SHIP_VIA, FREIGHT, SHIP_NAME, SHIP_ADDRESS, SHIP_CITY, SHIP_REGION, SHIP_POSTAL_CODE, SHIP_COUNTRY)
VALUES (10249, 2, 1, TO_DATE('1996-07-05', 'YYYY-MM-DD'), TO_DATE('1996-08-16', 'YYYY-MM-DD'), TO_DATE('1996-07-10', 'YYYY-MM-DD'), 1, 11.61, 'Toms Spezialitaten', 'Luisenstr. 48', 'Munster', NULL, '48409', 'Germany');
INSERT INTO ORDERS (ORDER_ID, CUSTOMER_ID, EMPLOYEE_ID, ORDER_DATE, REQUIRED_DATE, SHIPPED_DATE, SHIP_VIA, FREIGHT, SHIP_NAME, SHIP_ADDRESS, SHIP_CITY, SHIP_REGION, SHIP_POSTAL_CODE, SHIP_COUNTRY)
VALUES (10250, 3, 1, TO_DATE('1996-07-08', 'YYYY-MM-DD'), TO_DATE('1996-08-05', 'YYYY-MM-DD'), TO_DATE('1996-07-12', 'YYYY-MM-DD'), 2, 65.83, 'Hanari Carnes', 'Rua do Comercio, 12', 'Rio de Janeiro', 'RJ', '05454-000', 'Brazil');

-- ORDER_DETAILS
INSERT INTO ORDER_DETAILS (ORDER_ID, PRODUCT_ID, UNIT_PRICE, QUANTITY, DISCOUNT)
VALUES (10248, 11, 14, 12, 0);
INSERT INTO ORDER_DETAILS (ORDER_ID, PRODUCT_ID, UNIT_PRICE, QUANTITY, DISCOUNT)
VALUES (10248, 42, 9.8, 10, 0);
INSERT INTO ORDER_DETAILS (ORDER_ID, PRODUCT_ID, UNIT_PRICE, QUANTITY, DISCOUNT)
VALUES (10248, 72, 34.8, 5, 0);
INSERT INTO ORDER_DETAILS (ORDER_ID, PRODUCT_ID, UNIT_PRICE, QUANTITY, DISCOUNT)
VALUES (10249, 14, 18.6, 9, 0);
INSERT INTO ORDER_DETAILS (ORDER_ID, PRODUCT_ID, UNIT_PRICE, QUANTITY, DISCOUNT)
VALUES (10249, 51, 42.4, 40, 0);
INSERT INTO ORDER_DETAILS (ORDER_ID, PRODUCT_ID, UNIT_PRICE, QUANTITY, DISCOUNT)
VALUES (10250, 41, 9.65, 10, 0);
INSERT INTO ORDER_DETAILS (ORDER_ID, PRODUCT_ID, UNIT_PRICE, QUANTITY, DISCOUNT)
VALUES (10250, 51, 42.4, 35, 0.15);
INSERT INTO ORDER_DETAILS (ORDER_ID, PRODUCT_ID, UNIT_PRICE, QUANTITY, DISCOUNT)
VALUES (10250, 65, 21.05, 15, 0.15);

COMMIT;

PROMPT ============================================
PROMPT DATOS NORTHWIND CARGADOS CORRECTAMENTE
PROMPT ============================================

SELECT COUNT(*) as TOTAL_CATEGORIAS FROM CATEGORIES;
SELECT COUNT(*) as TOTAL_SUPPLIERS FROM SUPPLIERS;
SELECT COUNT(*) as TOTAL_EMPLOYEES FROM EMPLOYEES;
SELECT COUNT(*) as TOTAL_CUSTOMERS FROM CUSTOMERS;
SELECT COUNT(*) as TOTAL_PRODUCTS FROM PRODUCTS;
SELECT COUNT(*) as TOTAL_ORDERS FROM ORDERS;
SELECT COUNT(*) as TOTAL_ORDER_DETAILS FROM ORDER_DETAILS;
